#index:
#    path: /
#    controller: App\Controller\DefaultController::index
testmodule:
    path:   /test/
    controller: App\Controller\TestController::index


getform:    
    path:   /getform/
    controller: App\Controller\TestController::getFormRequest
    methods: POST
